version: '3'
services:
  mysql:
    image: mysql:8.0.23
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - $MYSQL_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
  be:
    container_name: "rails"
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - mysql
    environment:
      - ENV_MODE=dev
      - MYSQL_CONTAINER_NAME=bitflyer_rails_mysql
    ports:
      - $BE_PORT:3000
    volumes:
      - .:/usr/src/app
    command: ["rails", "server", "-b", "0.0.0.0"]
    tty: true
    stdin_open: true
  fe:
    container_name: "nuxt"
    build:
      context: ./
      dockerfile: ./FE/Dockerfile
    environment:
      TZ: Asia/Tokyo
      API_BASE_URL: $API_BASE_URL
    command: ['/bin/bash', '-c', 'NUXT_HOST=0.0.0.0 yarn run dev']
    working_dir: /usr/src/app/FE
    volumes:
      - ./:/usr/src/app
    ports:
      - $WEB_PORT:3000
    environment:
      - HOST=0.0.0.0
